language: python
python:
- '2.7'
- '3.5'
- '3.6'
script:
- PYTHONPATH=`pwd` pytest -s ./tests
deploy:
  provider: pypi
  user: lensonp
  password:
    secure: pDWV43bLQ8EDYA7F45QqTuuSYyxm+sU1w3M6829cxiUdMUXZupvmo/GQdMKb9t2sbLlQrH/9PG70IohuJVMPfJFzwkFE3s+GiTIcuED8r9sI2Gn3TDByFyhzKRVnmBifXuifwA4/RkoFyUoMZ5NDzzqhbd4aJ53D/JTPkfSaEreel3kakchHLNC+x0wEbexREq6FlLFQup6+9wgc6y0L8kMwgcZNasFCpfGRFsk9xhkqoUuKO0yU2S0dsvOPh8CcSIfcHbTq+BXnbuChesAeI2LQg9wRDUj9PJVDfak+ZiZVQryZzGxtrW0s4DWazZr/IPcU5n2DQWmxZsT7pb7VRN9wOrSR7T8N56sp21arJw0SrZgEzqo5fURKOhQ+JTDyHLE/B5nv9AHzDoOpLUlor730QiF4eyvoLLLlYGU/OC3lMhiLWgFPGxuhm+zgaPLDUOVZ4oxKiI5Q4caskqwUUGTr3X1hi3qeWLuPjFyLeZ6iyMXiZgB1297KzLeqmSiiENUSPZWlRyrHiEqBek1S6TMizNKEpO4ufeQ4Z9GYlzqeILQmNuvEo09FIeOOvSPVM4H74eeeHdYoX19UXTEc/BOVULpdYEECXgiIHOt2abDWzFLI1rldWPEH+CTyZa6ozkNE0D4iVaOaV4Btibz/V8Gp6FisfvZFxla6lprV2eg=
  on:
    distributions: sdist bdist_wheel
    branch: master
